//CREATE_TRIGGER

CREATE OR REPLACE TRIGGER TEST_TRIGGER
    AFTER DELETE OR INSERT OR UPDATE ON DB2_TEST 
        FOR EACH ROW
        BEGIN
         IF INSERTING OR UPDATING THEN
            MERGE INTO DB2_TEST@DB2 d
            USING (SELECT :NEW.TEST_ID AS TEST_ID, :NEW.test_name AS test_name FROM DUAL) s
            ON (d.TEST_ID = s.TEST_ID)
            WHEN MATCHED THEN 
                UPDATE SET d.test_name= s.test_name
            WHEN NOT MATCHED THEN
                INSERT(d.test_id,d.test_name) VALUES(s.TEST_ID,s.test_name);
            END IF;

         IF DELETING THEN
            DELETE FROM DB2_TEST@DB2 d
             WHERE d.TEST_ID = :OLD.TEST_ID;
         END IF;
    COMMIT;
END;
/
INSERT INTO  DB2_TEST(TEST_ID,TEST_NAME) VALUES(14,'TRIGGER TEST');

DROP TRIGGER TEST_TRIGGER;

INSERT INTO DB2_TEST(TEST_ID,TEST_NAME) VALUES(10,'TRIGGER TEST1');
SELECT * FROM DB2_TEST;
SELECT * FROM DB2_TEST@DB2;
DELETE FROM DB2_TEST WHERE TEST_ID = 10;