CREATE DATABASE LINK db2
CONNECT TO p7zhang IDENTIFIED BY "03178102"
USING
'(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle12c.scs.ryerson.
ca)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl12c)))';
SELECT * FROM p7zhang.DB2_TEST@db2;
CREATE TABLE db2_test(
test_id number PRIMARY KEY,
test_name VARCHAR2(50)
);