CREATE TABLE EMPLOYEES (
emp_id NUMBER PRIMARY KEY,
Name VARCHAR2(50) NOT NULL,
Position VARCHAR2(50) NOT NULL,
Salary DECIMAL(10,2) CHECK (Salary >=0),
Bonus DECIMAL(10,2) CHECK (Bonus>=0)
);


DROP TABLE EMPLOYEES;
SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEES@DB2;