--Season 02
--01 READ COMMITTED: Repeatable Read
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM EMPLOYEES@DB1;
UPDATE EMPLOYEES@DB1 SET Salary =Salary - 3000 WHERE emp_id = 1;
COMMIT;

--Season 02
--02 READ COMMITTED: Phantom Read
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM EMPLOYEES@DB1;
SELECT * FROM EMPLOYEES@DB1 WHERE POSITION='Executive Assistant';
COMMIT;

--Season 02
--03 READ SERIALIZABL: Repeatable Read Test
COMMIT;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM EMPLOYEES@DB1;
UPDATE EMPLOYEES@DB1 SET Salary =Salary - 3100 WHERE emp_id = 1;

--Season 02
--04 READ SERIALIZABL: Phantom Read Test
COMMIT;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SELECT * FROM EMPLOYEES@DB1 WHERE POSITION='Executive Assistant';
